#!/bin/bash
gcc -o init linktable.c menu.c main.c -m32 -static -lpthread
sudo mount -o loop rootfs.img root
sudo cp init root/    # 编译好的init
sudo umount root
qemu-system-i386 -curses -kernel ../bzImage -initrd rootfs.img -append "root=/dev/ram init=/init"
